sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
cache:
  directories:
    - node_modules
before_script:
  - echo "before_script"
script:
  - npm run lint
  - npm run build
after_script:
  - echo "after_script"
